### ISSUE TITLE
Type Error in an utility function

### ISSUE THREAD

**Issue by nimrodVarga** [OFAI/partitura#1]
In utils/music.py

the function "pitch_spelling_to_midi_pitch(step, alter, octave)"

uses the parameter "octave" directly as an integer, however it is of type String

this is simply fixed by converting the parameter to an int before usage

**Comment by mgrachten** [comment]
Are you referring to a specific call of the `pitch_spelling_to_midi_pitch` function somewhere in the repo? Rather than implicit conversion I would prefer a doc-string (which should be added anyway) that says that octave should be an integer.

**Comment by nimrodVarga** [comment]
Ah, wait, I created notes where I wrote the octave as a string instead of an int. I would then suggest to also add such a doc-string to the class Note, since I followed the XML convention of writing integers as strings

**Comment by mgrachten** [comment]
Agreed, documenting the Note class properly should avoid this error. I am working on it.

**Comment by mgrachten** [comment]
The documentation on the constructor arguments of the Note class (among other things) has been added in d90a040. Closing this issue.
