### ISSUE TITLE
Undefined Variable Error

### ISSUE THREAD

**Issue by nimrodVarga** [OFAI/partitura#2]
In **_score.py_**, in the method **__cleanup_point_** of the class **_Part_**
**_self._remove_point_** is called with _**o.end**_, however _**o**_ is not defined within the scope of the method

I think the intention was to simply pass the parameter _**tp**_ onto **_self._remove_point_** and that definitely fixes the error, however, not sure if it is intended that way.

**Comment by mgrachten** [comment]
> I think the intention was to simply pass the parameter tp onto _self.remove_point and that definitely fixes the error, however, not sure if it is intended that way.

Yes, that is the intention. Fixed by https://github.com/OFAI/partitura/commit/a30fda1e21a2c43beaf0a47446b1bdd24c422504
