### ISSUE TITLE
Matchfile version 1 error?

### ISSUE THREAD

**Issue by aggelosgkiokas** [OFAI/partitura#5]
file importmatch.py line 525:
pattern_v1 = MatchNote.pattern + '-' + MatchNote.pattern_v1
instead of:
pattern_v1 = MatchSNote.pattern + '-' + MatchNote.pattern_v1

**Comment by neosatrapahereje** [comment]
Hi Aggelos. Thanks for finding this error. I corrected the problem as you suggest in the **develop branch** (in this [commit](https://github.com/OFAI/partitura/commit/8444c7d74ee3295314e4376795b6f302c4c9396b)). 

We are planning to do a new release in the master branch in a few weeks (after the deadline for ISMIR). I would recommend that you use the develop branch, as it is up-to-date with new features.

We would be happy if you would like to contribute more things to partitura (bug fixes, new features, etc). You can make future contributions (i.e., pull requests) directly to the develop branch.

Cheers,

Carlos
