### ISSUE TITLE
incorrect doc string for estimate_key

### ISSUE THREAD

**Issue by mgrachten** [OFAI/partitura#6]
The documentation for the estimate_key function says that it returns a triplet of root, mode, and fifths, but in reality it only returns a string representation of the root+mode.

**Comment by neosatrapahereje** [comment]
Do you think it would be more useful to have `estimate_key` return root, mode and fifths? Otherwise, I'll simply update the doc string.

**Comment by mgrachten** [comment]
updating the doc string is sufficient I think.

**Comment by neosatrapahereje** [comment]
The doc string is updated in `develop` in commit 79fd680.

**Comment by mgrachten** [comment]
Yes, closing.
