### ISSUE TITLE
Import_match Create Part error.

### ISSUE THREAD

**Issue by melkisedeath** [OFAI/partitura#8]
**Key Error occurs when load_match function is called with create_part = True. Issue resolved when old_part_generator=True.**

> There seems to be an issue with some files in which the position of the notes in the score (from the cells with bar:beat_in_bar and beat_offset) seems to not match with the position of the notes using the onset_in_beats cell. part_from_matchfile_old uses the onset_in_beats information from the Matchfile, whereas part_from_matchfile uses the other (redundant) information. 
> It seems that bar_times does not have an element starting at 0, which means that either the position of that bar is incorrectly coded in the match file, or there is something else going on. 
> 

_Using current partitura develop branch_

```

KeyError                                  Traceback (most recent call last)

<ipython-input-16-079fc90cb3e0> in <module>
      1 from basismixer.performance_codec import to_matched_score
      2 
----> 3 ppart, alignment, spart = partitura.load_match( match_file_path)

~\AppData\Local\Programs\Python\Python38\lib\site-packages\partitura\io\importmatch.py in load_match(fn, create_part, pedal_threshold, first_note_at_zero, old_part_generator)
   1131             spart = part_from_matchfile_old(mf)
   1132         else:
-> 1133             spart = part_from_matchfile(mf)
   1134     ###### Alignment ########
   1135     alignment = alignment_from_matchfile(mf)

~\AppData\Local\Programs\Python\Python38\lib\site-packages\partitura\io\importmatch.py in part_from_matchfile(mf)
   1329     for (ts_beat_time, ts_bar, (ts_beats, ts_beat_type)) in ts:
   1330         #import pdb; pdb.set_trace()
-> 1331         bar_start_divs = int(divs * (bar_times[ts_bar] - offset))  # in quarters
   1332         bar_start_divs = max(0,bar_start_divs)
   1333         part.add(score.TimeSignature(ts_beats, ts_beat_type), bar_start_divs)

KeyError: 0

```

**Comment by mgrachten** [comment]
Thanks for reporting this issue. Would you care to share the match file that is causing the problem with us?

**Comment by melkisedeath** [comment]
The match file belongs to the match_zei alignments aligned_performance_data dataset:
> alignments_match_zei_beethoven_op002_no2_mv1.match 

I cannot upload the file as it isn't supported. Nevertheless, to any future encounter of any error on partitura I keep a history of all files that caused the error.

**Comment by sildater** [comment]
Thanks for reporting, I will look into this.
