### ISSUE TITLE
Inform of limited key estimation options in doc string.

### ISSUE THREAD

**Issue by mgrachten** [OFAI/partitura#9]
https://github.com/OFAI/partitura/blob/d90a040a35bdc474609e79ea1ec704d84f4e2fd6/partitura/musicanalysis/key_identification.py#L119-L120

The documentation of the estimate_key function lists "krumhansl" and "temperley" as options, which is incorrect if "temperley" is not supported.

**Comment by neosatrapahereje** [comment]
For now, I removed the reference to `'temperley'` in the doc string of  `key_identification` (in commit 7f80862). I will add full support of the Temperley's Bayesian key estimation method (for now in branch `update_kid`)
